eureka:
  instance:
    hostname: discovery-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  cloud:
    config:
      override.system-properties: false