spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      port: 27020
      authentication-database: admin
      database: customer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8095