spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      username: ${USERNAME_MS_CUSTOMER_MONGO}
      password: ${PASSWORD_MS_CUSTOMER_MONGO}
      host: ${MONGO_HOST}
      port: 27020
      authentication-database: ${MONGO_AUTH_DB}
      database: ${MONGO_DATABASE}

server:
  port: 8099