spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      port: 27020
      authentication-database: admin
      database: customer

server:
  port: 8099