spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: mongo
      port: 27017
      username: root
      password: example
      authentication-database: admin
      database: customer

server:
  port: 8099