spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  datasource:
    username: rafaelswr
    password: 1223
    url: jdbc:postgresql://localhost:5436/order
    driver-class-name: org.postgresql.Driver

application:
  config:
    customer: http://localhost:8099/customer
    product: http://localhost:8989/product
    payment-service: http://localhost:9090/payment
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.Mapping: orderConfirmation:com.rafaelswr.order.kafka.OrderConfirmation



server:
  port: 8070
