spring:
  datasource:
    url: ${URL_MS_PRODUCT_PG}
    username: ${USERNAME_MS_PG}
    password: ${PASSWORD_MS_PG}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${USERNAME_MS_PG}
    password: ${PASSWORD_MS_PG}
    url: ${URL_MS_PRODUCT_PG}

server:
  port: 8989