version: "3"

services:
  gateway:
    container_name: "ms_gateway"
    image: ms/gateway
    ports:
      - "8022:8022"
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true