version: '3'

services:
  product:
    container_name: "ms_product"
    image: ms/product
    ports:
      - "8989:8989"
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true

