spring:
  devtools:
    restart:
      enabled: true
  main:
    banner-mode: off
  application:
    name: payment-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  datasource:
    url: jdbc:postgresql://postgres:5432/payment
    username: rafaelswr
    password: 1223
    driver-class-name: org.postgresql.Driver
server:
  port: 9090

application:
  config:
    order: http://order:8070/order
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.Mapping: paymentNotification:com.rafaelswr.paymentservice.kafka.PaymentNotification

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka