spring:
  devtools:
    restart:
      enabled: true
  main:
    banner-mode: off
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    order: http://localhost:8070/order
