create table if not exists category (
    category_id bigint not null primary key generated by default as identity,
    name varchar(255),
    description varchar(255),
    created_at timestamp default current_timestamp not null
);

create table if not exists product
(
    id bigint not null primary key generated by default as identity,
    name varchar(255),
    description varchar(255),
    created_at timestamp default current_timestamp not null,
    available_quantity integer,
    price numeric(38, 2),
    category_id bigint
        constraint fk_category references category
);

create sequence if not exists category_seq increment by 50;
create sequence if not exists product_seq increment by 50;