version: '3'

services:
  discovery-server:
    container_name: "ms_discovery"
    image: ms/discovery
    ports:
      - 8761:8761
    networks:
      - microservices-net


networks:
  microservices-net:
    external: true